include:
  - infra.yml
services:
  bot:
    build: 
      dockerfile: bot.Dockerfile

  backend:
    build: 
      dockerfile: backend.Dockerfile
    ports:
      - "8000:5000"
    depends_on:
      db:
        condition: service_healthy
    develop:   
      watch:
        - action: sync
          path: .
          target: /app