services:
  db:
    image: postgres
    hostname: $DB_HOST
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_NAME
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - pgdata:/var/lib/postgresql/data

  admin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_PASSWORD: $DB_PASSWORD
      PGADMIN_DEFAULT_EMAIL: $DB_EMAIL
    depends_on:
      - db 

volumes:
  pgdata: