services:
  db:
    image: postgres
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_NAME
      POSTGRES_PASSWORD: $DB_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - pgdata:/var/lib/postgresql/data

  admin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_PASSWORD: $DB_PASSWORD
      PGADMIN_DEFAULT_EMAIL: $DB_EMAIL
    depends_on:
      db:
        condition: service_healthy 

  backend:
    build: .
    ports:
      - "8000:5000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: