"""initial tables for students and examrecords

Revision ID: 731a2a9ebd1c
Revises: 
Create Date: 2025-10-10 16:19:24.610839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '731a2a9ebd1c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=True),
    sa.Column('lastname', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('examrecords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subjectname', sa.Enum('RU', 'MATH', 'EN', name='subjectname'), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('studentid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['studentid'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('examrecords')
    op.drop_table('students')
    # ### end Alembic commands ###
