"""replace_id_in_examrecords_with_composite_pk

Revision ID: 24bcf111e0ed
Revises: 731a2a9ebd1c
Create Date: 2025-10-10 21:14:53.902775

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "24bcf111e0ed"
down_revision: Union[str, Sequence[str], None] = "731a2a9ebd1c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "examrecords",
        "subjectname",
        existing_type=postgresql.ENUM(
            "RU",
            "MATH",
            "EN",
            "SOCIAL",
            "PHYSICS",
            "CHEM",
            "BIO",
            "GEO",
            "LIT",
            "IT",
            "HISTORY",
            "DE",
            "FR",
            "ES",
            "CN",
            name="subjectname",
        ),
        nullable=False,
    )
    op.alter_column(
        "examrecords", "studentid", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("examrecords", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "examrecords", sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False)
    )
    op.alter_column(
        "examrecords", "studentid", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "examrecords",
        "subjectname",
        existing_type=postgresql.ENUM(
            "RU",
            "MATH",
            "EN",
            "SOCIAL",
            "PHYSICS",
            "CHEM",
            "BIO",
            "GEO",
            "LIT",
            "IT",
            "HISTORY",
            "DE",
            "FR",
            "ES",
            "CN",
            name="subjectname",
        ),
        nullable=True,
    )
    # ### end Alembic commands ###
