"""added_on_delete_cascade_to_examrecords

Revision ID: 971b782a2499
Revises: 24bcf111e0ed
Create Date: 2025-10-12 17:20:57.682637

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "971b782a2499"
down_revision: Union[str, Sequence[str], None] = "24bcf111e0ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("examrecords_studentid_fkey"), "examrecords", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "examrecords", "students", ["studentid"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "examrecords", type_="foreignkey")
    op.create_foreign_key(
        op.f("examrecords_studentid_fkey"),
        "examrecords",
        "students",
        ["studentid"],
        ["id"],
    )
    # ### end Alembic commands ###
